# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20171207_1624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='tb_choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='tb_question',
        ),
    ]
